### ISSUE TITLE
db-migrate: command not found

### ISSUE THREAD

**Issue by alexhanh** [kunklejr/node-db-migrate#138]
Added db-migrate to package.json and ran npm install. On terminal bash, I get `db-migrate: command not found` after running. `./node_modules/db-migrate/bin/db-migrate` works though.

**Comment by toymachiner62** [comment]
How do you plan to solve this? By requiring it to be installed globally?

**Comment by wzrdtales** [comment]
Similarly like I did it in umigrate, there won't be a need to modify NODE_PATH or set it though. I feels always like NODE_PATH is to much unknown by everyone, just because it's not really documented in node.js. There was also a big discussion about global modules and that npm wont support them at all, with Isaac schlueter.

But at first I will just change the documentation to:
    npm install -g db-migrate

and add the notice to that if it is intended to be used local to use:
    node_modules/db-migrate/bin/db-migrate

instead.

**Comment by wzrdtales** [comment]
To add some Informations to this:

Even if db-migrate is installed globally, the migrations local will throw the error it can't find db-migrate, because NODE_PATH is unset.

I solved this by requiring the components in db-migrate itself globally and share them down to the migrations.

**Comment by toymachiner62** [comment]
Oh interesting. I'll look at the commit once it's complete.

**Comment by wzrdtales** [comment]
have found it, this issue I meant:
https://github.com/npm/npm/issues/823

**Comment by wzrdtales** [comment]
Thus I will solve the problem in db-migrate making it usable as a global and local module and so spare the nerves of many people who don't know about NODE_PATH has to be set if they want to use global modules and want to require them from the local module.

**Comment by mnassarhub** [comment]
facing the same issue with db-migrate using it globally or locally give me the same message `db-migrate: command not found` using windows, `"npm":"^8.1.2", "node":"16.13.1", "pg": "^8.7.3", db-migrate": "^0.11.13", "db-migrate-pg": "^1.2.2"`

**Comment by JacobNewton007** [comment]
> npm install -g db-migrate

How did you add it to your environmental variable
