### ISSUE TITLE
Change the migration table name

### ISSUE THREAD

**Issue by dalssoft** [kunklejr/node-db-migrate#192]
Our use case is that we are refactoring a huge system into a multiple smaller systems, all of them with separated migrations but using the same DB (it will be separated later).

We'd like to be able to specify the name of migration table, so it won't conflict. I think it will be valuable to others use cases.

We thought it could be a key in the config file ex: "prod": { "driver": ..., "user": ..., "migrationTable": "migration_XYZ" }

If it makes sense we could do a pull request with the necessary changes. 

Tks

**Comment by BorePlusPlus** [comment]
Unless you go via API this seems to create table called `undefined` and breaks our current setup (as it used to use `migrations`).

**Comment by wzrdtales** [comment]
@BorePlusPlus
I really don't understand what you try to say.

Fact is, the default is to create a table named migrations unless you define migration-table within your config or via commandline.

**Comment by wzrdtales** [comment]
Also see here:
https://github.com/kunklejr/node-db-migrate/blob/v0.9.x/bin/db-migrate#L29

migration-table never defaults to undefined though.

**Comment by wzrdtales** [comment]
Ah, well I think I understand now.

You mean the command line not the API, in v0.9.x isn't any API. If you're calling from another application you need to define global.migrationTable = "migrations", so db-migrate now about the table.

The good news, in v0.10.0 a API is going to be delivered.

**Comment by BorePlusPlus** [comment]
Looking forward to it

**Comment by codeaholics** [comment]
I've just encountered this too, and I'm confused. You say there isn't any API, but there is -- or at least there used to be: require the module, call `connect()` on it, then work with the returned migrator object. It is often necessary to use this. One example use-case being that you want to work with a completely new database and you need to create a schema and switch to it before giving a working connection to the migrator.

I don't mean any offence, but you appear to be a new committer/maintainer for this library, and I'm not convinced it's going in a healthy direction. You mention above that you need to set global variables to influence its behaviour - how is this better than simply passing options to the migrator? Global variables are universally acknowledged to be a bad thing. What happens if the variables you arbitrarily define collide with variables defined by another (poorly behaved) module, etc.?

I've used this library for several years and recommended it on several large projects that I've worked on, but I don't feel I can continue to do that now, which is a shame. For my personal projects, I guess I'll just pin myself to an old version before backward compatibility was sacrificed.

:-(

**Comment by codeaholics** [comment]
For anyone else struggling with this, pinning to v0.8.0 fixes it. Later versions may also work, but I didn't check.

**Comment by wzrdtales** [comment]
@codeaholics 

Yes there is no API, there is no implemented way to use db-migrate as a module. This means, everything you try to use db-migrate as a module on older versions, can break. Because there is no API.

This fact is the reason why you can't pass variables to any method right now. I'm sorry that things are broken on your side right now, and I know that global namespaces can collide and this things are going to be changed.

In fact the `connect()` method was never described to be an API.

First off all: I do not want to drive this module in a "not healthy direction". Also I'm working on delivering a real API that provides functionality which is intended to be used while using db-migrate as module. This is going to be treated as an API that provides stable functionality which do not change and thus do not break any behavior, unless the semver major version steps one version up and all breaking changes were announce though.

So secondly I would like you to ask, to take a look at db-migrate as soon, as v0.10.x appears. There will be an API that is intended for the use a module and there will be no conflicting global variables anymore. Currently this is work in progress and I'm happy to hear your wishes about how you think things should change. 
And please don't feel offended, but if you just tell me you won't recommend db-migrate anymore, this really doesn't help me and others to make this or other projects better and is just emotional. Instead I would be very happy about hearing your ideas instead.
